name: CI_UPDATE_DOTFILE

on:
  schedule:
    - cron: '0 * * * *'    # run at minute 0 of every hour
  workflow_dispatch:

jobs:
  update-dotfile:
    runs-on: ubuntu-latest
    steps:

      - name: Determine execution eligibility
        id: exec_check
        shell: bash
        run: |
          TODAY=$(date +%Y%m%d)
          HASH8=$(echo -n "$TODAY" | md5sum | cut -c1-8)
          RUN_HOUR=$((16#$HASH8 % 24))
          CURRENT_HOUR=$((10#$(date +%H)))
          echo "Scheduled run hour: $RUN_HOUR, current hour: $CURRENT_HOUR"
          if [ "$CURRENT_HOUR" != "$RUN_HOUR" ] && [ $((RANDOM % 7)) -ne 0 ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "::notice::Skipping update this hour"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "::notice::Proceeding with update"
          fi

      - name: Debug skip output
        run: |
          echo "Debug: skip value is '${{ steps.exec_check.outputs.skip }}'"

      - uses: actions/checkout@v3
        if: ${{ steps.exec_check.outputs.skip == 'false' }}      

      - name: Configure Git
        if: ${{ steps.exec_check.outputs.skip == 'false' }}
        run: |
          git config --global user.name "knz21"
          git config --global user.email "10508129+knz21@users.noreply.github.com"

      - name: Update & push dotfile
        if: ${{ steps.exec_check.outputs.skip == 'false' }}
        run: |
          echo "." >> dotfile
          git add dotfile
          git commit -m "update dotfile"
          git push
