name: CI_UPDATE_DOTFILE
on:
  schedule:
    - cron: '0 0-18/2 * * *'
  workflow_dispatch:
jobs:
  build:
    if: $(shuf -i 0-2 -n 1) % 2 == 1
    runs-on: ubuntu-latest
    steps:
#       - id: random
#         run: echo "PROCEED=$((RANDOM%3>0))" >> $GITHUB_ENV
#         shell: bash

#       - if: env.PROCEED
#         name: Cancelling
#         uses: andymckay/cancel-action@0.2

#       - if: env.PROCEED
#         name: Waiting for cancellation
#         run: sleep 60
      
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name knz21
          git config --global user.email 10508129+knz21@users.noreply.github.com
          echo "." >> dotfile
          git add dotfile
          git commit -m "update dotfile"
          git push
