name: CI_UPDATE_DOTFILE
on:
  schedule:
    - cron: '30 6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name knz21
          git config user.email 10508129+knz21@users.noreply.github.com
          echo "." >> dotflie
          git add dotfile
          git commit -m "update dotfile"
          git push
